version: '2'

networks:
  app-tier:
    driver: bridge

services:
  mongodb:
    image: docker.io/bitnami/mongodb:6.0
    environment:
      - MONGODB_USERNAME=sa
      - MONGODB_PASSWORD=short123
      - MONGODB_DATABASE=urlshortner
    networks:
      - app-tier
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami/mongodb'
  
  mongo-express:
    image: mongo-express
    environment:
      - MONGODB_PORT=27017
      - MONGODB_USERNAME=sa
      - MONGODB_PASSWORD=short123
      - MONGODB_DATABASE=urlshortner
    networks:
      - app-tier
    links:
      - mongodb
    ports:
      - "8081:8081"

volumes:
  mongodb_data:
    driver: local
